version: 2

jobs:
  build:
    docker:
      - image: openjdk:8
    working_directory: ~/src
    steps:
      - checkout
      - restore_cache:
          key: lambda-route53-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
        paths:
          - ~/.m2
        key: lambda-route53-{{ checksum "pom.xml" }}
      - run: mvn -B package shade:shade
      - store_test_results:
        path: target/surefire-reports
      - store_artifacts:
        path: target/lambda-route53-updates-*.jar

#dependencies:
#  pre:
#    - go get github.com/tcnksm/ghr
#  override:
#    - mvn -B package shade:shade
#
#test:
#  post:
#    - install -D -m644 target/lambda-route53-updates-*.jar $CIRCLE_ARTIFACTS
#
#deployment:
#  release:
#    tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
#    commands:
#      - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` $CIRCLE_ARTIFACTS
